diff --git a/makefile b/makefile
index ad57e43..38b9cb4 100644
--- a/makefile
+++ b/makefile
@@ -11,10 +11,10 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 
-CFLAGS := -O3
-DFLAGS := -g
-CC := gcc
-BINDIR := /usr/bin
+CFLAGS ?= -O3
+DFLAGS ?= -g
+CC ?= gcc
+BINDIR ?= /usr/bin
 
 SRC := src
 BIN := bin
@@ -22,25 +22,25 @@ DAT := dat
 ALL := $(SRC)/workers.c $(SRC)/data.c $(SRC)/gmm_base.c $(SRC)/gmm_class.c $(SRC)/gmm_train.c $(SRC)/gmm_merge.c
 
 all:
-	$(CC) $(CFLAGS) -fprofile-generate $(ALL) $(SRC)/train.c -o $(BIN)/gmmtrain -pthread -lz -lm
+	$(CC) $(CFLAGS) -fprofile-generate $(ALL) $(SRC)/train.c -o $(BIN)/gmmtrain $(LDFLAGS) -pthread -lz -lm
 	chmod +x $(BIN)/gmmtrain
-	$(BIN)/gmmtrain -d $(DAT)/data.gz -m $(DAT)/data.gmm -n 128 -s 0.1 -u 0.9 -r $(DAT)/train.json
-	$(CC) $(CFLAGS) -fprofile-use -fprofile-correction $(ALL) $(SRC)/train.c -o $(BIN)/gmmtrain -pthread -lz -lm
+	$(BIN)/gmmtrain -t 1 -d $(DAT)/data.gz -m $(DAT)/data.gmm -n 128 -s 0.1 -u 0.9 -r $(DAT)/train.json
+	$(CC) $(CFLAGS) -fprofile-use -fprofile-correction $(ALL) $(SRC)/train.c -o $(BIN)/gmmtrain $(LDFLAGS) -pthread -lz -lm
 	strip $(BIN)/gmmtrain
 	chmod +x $(BIN)/gmmtrain
 	rm -f *.gcda
-	$(CC) $(CFLAGS) -fprofile-generate $(ALL) $(SRC)/class.c -o $(BIN)/gmmclass -pthread -lz -lm
+	$(CC) $(CFLAGS) -fprofile-generate $(ALL) $(SRC)/class.c -o $(BIN)/gmmclass $(LDFLAGS) -pthread -lz -lm
 	chmod +x $(BIN)/gmmclass
-	$(BIN)/gmmclass -d $(DAT)/data.gz -m $(DAT)/data.gmm -w $(DAT)/data.gmm -r $(DAT)/class.json
-	$(BIN)/gmmclass -d $(DAT)/data.gz -m $(DAT)/data.gmm -w $(DAT)/data.gmm
-	$(CC) $(CFLAGS) -fprofile-use -fprofile-correction $(ALL) $(SRC)/class.c -o $(BIN)/gmmclass -pthread -lz -lm
+	$(BIN)/gmmclass -t 1 -d $(DAT)/data.gz -m $(DAT)/data.gmm -w $(DAT)/data.gmm -r $(DAT)/class.json
+	$(BIN)/gmmclass -t 1 -d $(DAT)/data.gz -m $(DAT)/data.gmm -w $(DAT)/data.gmm
+	$(CC) $(CFLAGS) -fprofile-use -fprofile-correction $(ALL) $(SRC)/class.c -o $(BIN)/gmmclass $(LDFLAGS) -pthread -lz -lm
 	strip $(BIN)/gmmclass
 	chmod +x $(BIN)/gmmclass
 	rm -f *.gcda
 
 debug:
-	$(CC) $(DFLAGS) $(ALL) $(SRC)/class.c -o $(BIN)/gmmclass -pthread -lz -lm
-	$(CC) $(DFLAGS) $(ALL) $(SRC)/train.c -o $(BIN)/gmmtrain -pthread -lz -lm
+	$(CC) $(DFLAGS) $(ALL) $(SRC)/class.c -o $(BIN)/gmmclass $(LDFLAGS) -pthread -lz -lm
+	$(CC) $(DFLAGS) $(ALL) $(SRC)/train.c -o $(BIN)/gmmtrain $(LDFLAGS) -pthread -lz -lm
 	chmod +x $(BIN)/gmmclass
 	chmod +x $(BIN)/gmmtrain
 
