{% set name = "em4gmm" %}
{% set version = environ["GIT_FULL_HASH"][0:7] %}
{% if "GIT_DESCRIBE_TAG" in environ %}
{%     set version = environ["GIT_DESCRIBE_TAG"] | replace("v", "") |replace("-", "_") %}
{%     if "GIT_DESCRIBE_NUMBER" in environ and environ["GIT_DESCRIBE_NUMBER"] | int > 0 %}
{%         set version = version ~ "_" ~ environ["GIT_BUILD_STR"] %}
{%     endif %}
{% endif %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_url: https://github.com/juandavm/em4gmm.git
  git_rev: master
  patches:
  - makefile.patch

build:
  script: |
    make
    make BINDIR="$PREFIX/bin" install

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib

about:
  home: https://github.com/juandavm/em4gmm.git
  license: GPL2
